/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './ro./routes/_auth/route
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-upp'
import { Route as authRequestPasswordResetRouteI./route./routes/(auth)/reset-passwordord-resetassword-reset'
import { Route as authSignInIndexRouteImport } from '././route./routes/(auth)/request-password-reset
import { Route as authSignInSsoRouteImport } from '././routes/(auth)/sign-in/indexest-password-reset
import { Route as authSignInMagicLinkRouteImport } ./routes/(auth)/sign-in/ssondexagic-link'
./routes/_auth/sign-in/sso./routes/(auth)/sign-in/magic-link
const AboutRoute = AboutRouteImport.update({./routes/_auth/sign-in/magic-link
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/(auth)/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const authRequestPasswordResetRoute =
  authRequestPasswordResetRouteImport.update({
    id: '/(auth)/request-password-reset',
    path: '/request-password-reset',
    getParentRoute: () => rootRouteImport,
  } as any)
const authSignInIndexRoute = authSignInIndexRouteImport.update({
  id: '/(auth)/sign-in/',
  path: '/sign-in/',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInSsoRoute = authSignInSsoRouteImport.update({
  id: '/(auth)/sign-in/sso',
  path: '/sign-in/sso',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInMagicLinkRoute = authSignInMagicLinkRouteImport.update({
  id: '/(auth)/sign-in/magic-link',
  path: '/sign-in/magic-link',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/request-password-reset': typeof authRequestPasswordResetRoute
  '/sign-up': typeof authSignUpRoute
  '/sign-in/magic-link': typeof authSignInMagicLinkRoute
  '/sign-in/sso': typeof authSignInSsoRoute
  '/sign-in': typeof authSignInIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/request-password-reset': typeof authRequestPasswordResetRoute
  '/sign-up': typeof authSignUpRoute
  '/sign-in/magic-link': typeof authSignInMagicLinkRoute
  '/sign-in/sso': typeof authSignInSsoRoute
  '/sign-in': typeof authSignInIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/(auth)/request-password-reset': typeof authRequestPasswordResetRoute
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(auth)/sign-in/magic-link': typeof authSignInMagicLinkRoute
  '/(auth)/sign-in/sso': typeof authSignInSsoRoute
  '/(auth)/sign-in/': typeof authSignInIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/request-password-reset'
    | '/sign-up'
    | '/sign-in/magic-link'
    | '/sign-in/sso'
    | '/sign-in'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/request-password-reset'
    | '/sign-up'
    | '/sign-in/magic-link'
    | '/sign-in/sso'
    | '/sign-in'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/(auth)/request-password-reset'
    | '/(auth)/sign-up'
    | '/(auth)/sign-in/magic-link'
    | '/(auth)/sign-in/sso'
    | '/(auth)/sign-in/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  authRequestPasswordResetRoute: typeof authRequestPasswordResetRoute
  authSignUpRoute: typeof authSignUpRoute
  authSignInMagicLinkRoute: typeof authSignInMagicLinkRoute
  authSignInSsoRoute: typeof authSignInSsoRoute
  authSignInIndexRoute: typeof authSignInIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/request-password-reset': {
      id: '/(auth)/request-password-reset'
      path: '/request-password-reset'
      fullPath: '/request-password-reset'
      preLoaderRoute: typeof authRequestPasswordResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in/': {
      id: '/(auth)/sign-in/'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in/sso': {
      id: '/(auth)/sign-in/sso'
      path: '/sign-in/sso'
      fullPath: '/sign-in/sso'
      preLoaderRoute: typeof authSignInSsoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in/magic-link': {
      id: '/(auth)/sign-in/magic-link'
      path: '/sign-in/magic-link'
      fullPath: '/sign-in/magic-link'
      preLoaderRoute: typeof authSignInMagicLinkRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  authRequestPasswordResetRoute: authRequestPasswordResetRoute,
  authSignUpRoute: authSignUpRoute,
  authSignInMagicLinkRoute: authSignInMagicLinkRoute,
  authSignInSsoRoute: authSignInSsoRoute,
  authSignInIndexRoute: authSignInIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
